export const GET_PRODUCTS_REQUEST = 'product/GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_DATA_SUCCESS = 'product/GET_PRODUCTS_DATA_SUCCESS';
export const GET_PRODUCTS_DATA_FAIL = 'product/GET_PRODUCTS_DATA_FAIL';